name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6' # Use the desired Flutter version

    - name: Flutter Pub Get
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Build App Bundle
      run: flutter build appbundle --release

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Upload AAB
      uses: actions/upload-artifact@v2
      with:
        name: app-release.aab
        path: build/app/outputs/bundle/release/app-release.aab
